### ISSUE TITLE
VirusTotal flags neuralhash_128x96_seed1.dat with Trojan:Script/Wacatac.B!ml from Microsoft

### ISSUE THREAD

**Issue by laserjobs** [AsuharietYgvar/AppleNeuralHash2ONNX#3]
File distributed by Apple
312344458ca5468eced6f50163c09d88dbc9f3470891f1b078852b01c9a0fce9
neuralhash_128x96_seed1.dat
48.13 KB
known-distributor
Microsoft: Trojan:Script/Wacatac.B!ml

**Comment by hackerfactor** [comment]
I just submitted the same file (same sha256) to VirusTotal. It came up clean.

**Comment by laserjobs** [comment]
> I just submitted the same file (same sha256) to VirusTotal. It came up clean.

It is a common issue with Microsoft and a lot of people calling it a false positive
https://www.hybrid-analysis.com/sample/312344458ca5468eced6f50163c09d88dbc9f3470891f1b078852b01c9a0fce9

**Comment by hackerfactor** [comment]
How very odd... even with a false-positive, I would have expected VirusTotal to act consistently.
Instead of a file upload, I threw it on my web server and did a URL upload:
  https://www.virustotal.com/gui/url/d06fee99d21d326b84fcdee76963ea8bf861a25c0f3e112b1286d8077cf19b61/detection

I don't even see Microsoft listed as one of the scanners!

Update: Confirmed. Doing a file-upload to VirusTotal triggers the Microsoft scanner with the false-positive match.  The same scan with a URL upload does not trigger the Microsoft scanner and no false-positive.

Update: Jotti comes up clean.

**Comment by LiEnby** [comment]
I get "Win32:Wactac.b!ml" on all my applications, KuromeSan/FlashPatcher used to have it I sent it to MS and they gave me a "HackTool/Patcher: instead ..

KuromeSan/GayMaker used to but I sent it to microsoft and they stopped 

KuromeSan/make-vita-afv still has it I think.

SilicaAndPina/CXML-Decompiler on BitBucket still has it as well 

I deal with this detection nearly every relesse someone will leave an issue saying its malware and its always fucking WacTac.b!ml

**Comment by overlisted** [comment]
that file is literally on every iphone right now, how can it be a trojan??

**Comment by laserjobs** [comment]
Has anyone actually looked at the file? I see a some ASCII at the beginning with "KRYSIA" repeated 3 times.

**Comment by AsuharietYgvar** [comment]
This file contains only a header and a bunch of floating point numbers. It's possible that somehow it matches a few bytes of a trojan. This is just a false alarm which is not uncommon for anti-virus softwares.
